feat: check paths before invoking unity
Unity gives the following error when the project path is incorrect :
> Couldn't set project path to: [path to UnityInvoker][project path]r\n

Which makes you thing there is a bug, because it appends the project path to the UnityInvoker lib path.
Now we chack path validity beforehand to output a better error :
> Error: ENOENT: no such file or directory, scandir 'E:\dev\mitm\mdc-unity-sandbox\mdc-compile-material-ab-with-crunch']